### ISSUE TITLE
Request for you to upload the code

### ISSUE THREAD

**Issue by shashank-suresh84** [JafferAbbas-codes/Online-Bookstore---MERN-Stack#1]
Hey! I just wanted to refer to the code of the bookstore web application,could you please upload it? And also on how to execute it

**Comment by shashanksuresh8402** [comment]
Please do upload the code and readme file stating how to execute the following code

**Comment by JafferAbbas-codes** [comment]
Hey @shashanksuresh8402,
The server and react code is in branches other than master i.e. "JafferAbbas" and "SyedaNarjisBatool" respectively.

Cheers.
